In [2]:
import pandas as pd

In [41]:
df = pd.read_csv("data/demographic.csv")
df

,title,genres,runtime,vote_average,vote_count,release_year,Action,Adventure,Animation,Comedy,...,History,Horror,Music,Mystery,Romance,Science Fiction,TV Movie,Thriller,War,Western
0,Toy Story,Animation; Comedy; Family,81.0,7.7,5415.0,1995,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
1,Jumanji,Adventure; Fantasy; Family,104.0,6.9,2413.0,1995,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Grumpier Old Men,Romance; Comedy,101.0,6.5,92.0,1995,0,0,0,1,...,0,0,0,0,1,0,0,0,0,0
3,Waiting to Exhale,Comedy; Drama; Romance,127.0,6.1,34.0,1995,0,0,0,1,...,0,0,0,0,1,0,0,0,0,0
4,Father of the Bride Part II,Comedy,106.0,5.7,173.0,1995,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45125,Robin Hood,Drama; Action; Romance,104.0,5.7,26.0,1991,1,0,0,0,...,0,0,0,0,1,0,0,0,0,0
45126,Century of Birthing,Drama,360.0,9.0,3.0,2011,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
45127,Betrayal,Action; Drama; Thriller,90.0,3.8,6.0,2003,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
45128,Satan Triumphant,NaN,87.0,0.0,0.0,1917,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
45129,Queerama,NaN,75.0,0.0,0.0,2017,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
# Sort 
df.sort_values("vote_average", ascending=False)

,title,genres,runtime,vote_average,vote_count,release_year,Action,Adventure,Animation,Comedy,...,History,Horror,Music,Mystery,Romance,Science Fiction,TV Movie,Thriller,War,Western
30718,Mortal Kombat: The Journey Begins,Action; Animation,54.0,10.0,1.0,1995,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
31691,Canal Zone,Documentary,174.0,10.0,1.0,1977,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
44549,Lad: A Yorkshire Story,NaN,96.0,10.0,1.0,2013,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
37671,Bowery Battalion,Comedy,69.0,10.0,1.0,1951,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
43186,Firefly,Comedy,84.0,10.0,1.0,1975,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32120,The Collection,NaN,64.0,0.0,0.0,1976,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21585,The Wet Parade,Drama; History; Romance,118.0,0.0,1.0,1932,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
21582,The Story of Maths,Documentary,240.0,0.0,0.0,2008,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21537,Setouchi Moonlight Serenade,Drama,117.0,0.0,0.0,1997,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
45129,Queerama,NaN,75.0,0.0,0.0,2017,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [42]:
# step 1 filter (duration, genre, runtime, etc)
genre = ["Animation"]
duration = (60, 150)
year = (2000, 2019)
topk = 20

In [43]:
df = df[df.release_year.between(year[0], year[1]) & 
        df.runtime.between(duration[0], duration[1]) & 
        df[genre].all(axis=1)]

df.head()

,title,genres,runtime,vote_average,vote_count,release_year,Action,Adventure,Animation,Comedy,...,History,Horror,Music,Mystery,Romance,Science Fiction,TV Movie,Thriller,War,Western
3161,The Tigger Movie,Animation; Family,77.0,6.3,146.0,2000,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3354,The Road to El Dorado,Adventure; Animation; Comedy; Family,89.0,7.0,892.0,2000,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
3484,Dinosaur,Animation; Family,82.0,6.2,563.0,2000,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3614,Titan A.E.,Animation; Action; Science Fiction; Family; Ad...,94.0,6.3,320.0,2000,1,1,1,0,...,0,0,0,0,0,1,0,0,0,0
3619,Chicken Run,Animation; Comedy; Family,84.0,6.5,1190.0,2000,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0

In [44]:
recommendation = df.sort_values("vote_average", ascending=False).head(topk)
recommendation

,title,genres,runtime,vote_average,vote_count,release_year,Action,Adventure,Animation,Comedy,...,History,Horror,Music,Mystery,Romance,Science Fiction,TV Movie,Thriller,War,Western
25671,Rocks in my Pockets,Comedy; Animation; Drama,88.0,9.4,5.0,2014,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
41890,Kizumonogatari Part 3: Reiketsu,Animation; Fantasy; Mystery,82.0,9.4,5.0,2017,0,0,1,0,...,0,0,0,1,0,0,0,0,0,0
26636,Lotte from Gadgetville,Adventure; Animation; Comedy; Family,81.0,9.0,4.0,2006,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
41846,Kizumonogatari Part 2: Nekketsu,Animation; Fantasy; Mystery,68.0,8.9,11.0,2016,0,0,1,0,...,0,0,0,1,0,0,0,0,0,0
35577,"Fuse, Memoirs of the Hunter Girl",Action; Animation; Drama; History,110.0,8.8,4.0,2012,1,0,1,0,...,1,0,0,0,0,0,0,0,0,0
43038,In This Corner of the World,Animation; Drama,128.0,8.7,19.0,2016,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
40018,Your Name.,Romance; Animation; Drama,106.0,8.5,1030.0,2016,0,0,1,0,...,0,0,0,0,1,0,0,0,0,0
28618,The Life and Mind of Mark DeFriest,Animation; Documentary,92.0,8.5,2.0,2014,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
41695,The Snow Queen 3: Fire and Ice,Family; Animation; Fantasy,80.0,8.5,2.0,2016,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
26159,The Littlest Angel,Animation; Family,84.0,8.5,2.0,2011,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
5471,Spirited Away,Fantasy; Adventure; Animation; Family,125.0,8.3,3968.0,2001,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
16754,Corto Maltese: Under the Sign of Capricorn,Adventure; Animation; Action,85.0,8.3,4.0,2002,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
40531,The Girl Without Hands,Animation,76.0,8.3,5.0,2016,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
31851,The Crisis of Civilization,Documentary; Animation; History,82.0,8.3,2.0,2012,0,0,1,0,...,1,0,0,0,0,0,0,0,0,0
40238,Over the Garden Wall,Adventure; Animation; Family; Fantasy,110.0,8.2,52.0,2014,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
9687,Howl's Moving Castle,Fantasy; Animation; Adventure,119.0,8.2,2049.0,2004,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
29095,Cheatin',Animation,72.0,8.2,10.0,2013,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
42373,My Entire High School Sinking Into the Sea,Animation,75.0,8.2,3.0,2016,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
24971,Song of the Sea,Family; Animation; Fantasy,93.0,8.1,420.0,2014,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
28741,The Garden of Sinners - Chapter 5: Paradox Spiral,Action; Animation; Drama; Mystery; Thriller,114.0,8.1,15.0,2008,1,0,1,0,...,0,0,0,1,0,0,0,1,0,0

In [16]:
# IMDB Weighted Rating 
# WR = Rv + Cm / v + m
# v = jumlah voting film tersebut
# m = syarat minimum vote (personalized/ quantile)
# R = rata-rata rating film itu
# C = rata-rata rating semua film

In [45]:
def imdb_score(df, q=0.9):
    df = df.copy()
    
    m = df.vote_count.quantile(q)
    C = (df.vote_average * df.vote_count).sum() / df.vote_count.sum()
    
    df = df[df.vote_count >= m]
    df["score"] = df.apply(lambda x: (x.vote_average * x.vote_count + C*m) / (x.vote_count + m), axis=1)
    
    return df

In [46]:
df = imdb_score(df)

In [47]:
recommendation = df.sort_values("vote_average", ascending=False).head(topk)
recommendation

,title,genres,runtime,vote_average,vote_count,release_year,Action,Adventure,Animation,Comedy,...,Horror,Music,Mystery,Romance,Science Fiction,TV Movie,Thriller,War,Western,score
40018,Your Name.,Romance; Animation; Drama,106.0,8.5,1030.0,2016,0,0,1,0,...,0,0,0,1,0,0,0,0,0,7.674753
5471,Spirited Away,Fantasy; Adventure; Animation; Family,125.0,8.3,3968.0,2001,0,1,1,0,...,0,0,0,0,0,0,0,0,0,8.001510
9687,Howl's Moving Castle,Fantasy; Animation; Adventure,119.0,8.2,2049.0,2004,0,1,1,0,...,0,0,0,0,0,0,0,0,0,7.748385
30208,Inside Out,Drama; Comedy; Animation; Family,94.0,7.9,6737.0,2015,0,0,1,1,...,0,0,0,0,0,0,0,0,0,7.760765
12693,WALLÂ·E,Animation; Family,98.0,7.8,6439.0,2008,0,0,1,0,...,0,0,0,0,0,0,0,0,0,7.668918
13710,Up,Animation; Comedy; Family; Adventure,96.0,7.8,7048.0,2009,0,1,1,1,...,0,0,0,0,0,0,0,0,0,7.678809
24383,Big Hero 6,Adventure; Family; Animation; Action; Comedy,102.0,7.8,6289.0,2014,1,1,1,1,...,0,0,0,0,0,0,0,0,0,7.666230
36082,Zootopia,Animation; Adventure; Family; Comedy,108.0,7.7,4961.0,2016,0,1,1,1,...,0,0,0,0,0,0,0,0,0,7.553646
15328,Toy Story 3,Animation; Family; Comedy,103.0,7.6,4710.0,2010,0,0,1,1,...,0,0,0,0,0,0,0,0,0,7.465088
23489,How to Train Your Dragon 2,Fantasy; Action; Adventure; Animation; Comedy;...,102.0,7.6,3163.0,2014,1,1,1,1,...,0,0,0,0,0,0,0,0,0,7.415234
6221,Finding Nemo,Animation; Family,100.0,7.6,6292.0,2003,0,0,1,0,...,0,0,0,0,0,0,0,0,0,7.494264
14965,How to Train Your Dragon,Fantasy; Adventure; Animation; Family,98.0,7.5,4319.0,2010,0,1,1,0,...,0,0,0,0,0,0,0,0,0,7.374371
11556,Ratatouille,Animation; Comedy; Family; Fantasy,111.0,7.5,4510.0,2007,0,0,1,1,...,0,0,0,0,0,0,0,0,0,7.378707
22656,The Lego Movie,Adventure; Animation; Comedy; Family; Fantasy,100.0,7.5,3127.0,2014,0,1,1,1,...,0,0,0,0,0,0,0,0,0,7.338290
14362,Fantastic Mr. Fox,Adventure; Animation; Comedy; Family,87.0,7.5,1206.0,2009,0,1,1,1,...,0,0,0,0,0,0,0,0,0,7.198949
4746,"Monsters, Inc.",Animation; Comedy; Family,92.0,7.5,6150.0,2001,0,0,1,1,...,0,0,0,0,0,0,0,0,0,7.406437
16108,Tangled,Animation; Family,100.0,7.4,3419.0,2010,0,0,1,0,...,0,0,0,0,0,0,0,0,0,7.271956
8223,The Incredibles,Action; Adventure; Animation; Family,115.0,7.4,5290.0,2004,1,1,1,0,...,0,0,0,0,0,0,0,0,0,7.309902
41203,Moana,Adventure; Animation; Family,107.0,7.3,3471.0,2016,0,1,1,0,...,0,0,0,0,0,0,0,0,0,7.196208
4168,Shrek,Adventure; Animation; Comedy; Family; Fantasy,90.0,7.3,4183.0,2001,0,1,1,1,...,0,0,0,0,0,0,0,0,0,7.210402